# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Miroslav Suchý <msuchy@redhat.com>, 2011.
# Xavier Conde Rueda <xaviconde@eresmas.com>, 2004-2005.
# Xavier Conde Rueda <xaviconde@eresmas.com>, 2004-2005, 2012.
# Jordi Mas <jmas@softcatala.org>, 2013
# Miroslav Suchý <msuchy@redhat.com>, 2011
# Xavier Conde Rueda <xaviconde@eresmas.com>, 2004-2005
# Xavier Conde Rueda <xaviconde@eresmas.com>, 2004-2005, 2012
# Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>, 2015. #zanata
# Jiri Dostal <jdostal@redhat.com>, 2018. #zanata
# Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-04-08 15:54+0200\n"
"PO-Revision-Date: 2024-02-22 13:42+0000\n"
"Last-Translator: David Medina <medipas@gmail.com>\n"
"Language-Team: Catalan <https://l10n.opensuse.org/projects/uyuni/spacewalk-"
"client-tools/ca/>\n"
"Language: ca\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: Weblate 4.9.1\n"

#: ../src/up2date_client/capabilities.py:94
#, python-format
msgid ""
"This client requires the server to support %s, which the current server does "
"not support"
msgstr ""
"Aquest client requereix que el servidor admeti %s, però el servidor actual "
"no ho admet."

#: ../src/up2date_client/config.py:162
#, python-format
msgid "%s was not found"
msgstr "no s'ha trobat %s"

#: ../src/up2date_client/rpcServer.py:56
msgid "Error: Server Unavailable. Please try later."
msgstr "Error: El servidor no està disponible. Si us plau, proveu-ho més tard."

#: ../src/up2date_client/rpcServer.py:182
msgid "ERROR: can not find server CA file"
msgstr "ERROR: no es pot trobar el fitxer CA del servidor"

#: ../src/up2date_client/rpcServer.py:220
msgid "Connection aborted by the user"
msgstr "La connexió va ser avortada per l'usuari"

#: ../src/up2date_client/rpcServer.py:268
msgid "Server has refused connection due to high load"
msgstr "El servidor ha refusat la connexió a causa d'una càrrega elevada"

#: ../src/up2date_client/up2dateErrors.py:47
#: ../src/up2date_client/up2dateErrors.py:80
#, python-format
msgid "class %s has no attribute '%s'"
msgstr "la classe %s no té cap atribut '%s'"

#: ../src/up2date_client/up2dateErrors.py:107
msgid "RPM error.  The message was:\n"
msgstr "S'ha produït un error en l'RPM. El missatge era:\n"

#: ../src/up2date_client/up2dateErrors.py:114
msgid "Password error. The message was:\n"
msgstr "S'ha produït un error en la contrasenya. El missatge era:\n"

#: ../src/up2date_client/up2dateErrors.py:118
msgid "RPM dependency error. The message was:\n"
msgstr "S'ha produït un error de dependències d'RPM. El missatge era:\n"

#: ../src/up2date_client/up2dateErrors.py:128
msgid "Error communicating with server. The message was:\n"
msgstr "S'ha produït un error en comunicar amb el servidor. El missatge era:\n"

#: ../src/up2date_client/up2dateErrors.py:135
msgid "File Not Found: \n"
msgstr "No s'ha trobat el fitxer: \n"

#: ../src/up2date_client/up2dateErrors.py:142
msgid "Delay error from server.  The message was:\n"
msgstr "S'ha produït un error de retard del servidor. El missatge era:\n"

#: ../src/up2date_client/up2dateErrors.py:178
msgid "Error validating data at server:\n"
msgstr "Error en validar les dades al servidor:\n"

#: ../src/up2date_client/up2dateErrors.py:191
msgid ""
"\n"
"Red Hat Network Classic is not supported.\n"
"    "
msgstr ""
"\n"
"Red Hat Network Classic no és compatible.\n"
"    "

#: ../src/up2date_client/up2dateErrors.py:197
msgid "The installation number is invalid"
msgstr "El número d'instal·lació no és vàlid"

#: ../src/up2date_client/up2dateErrors.py:200
msgid "Error parsing the oemInfo file at field:\n"
msgstr "Error en analitzar sintàcticament el fitxer oemInfo al camp:\n"

#: ../src/up2date_client/up2dateErrors.py:227
msgid "Network error: "
msgstr "Error de xarxa: "

#: ../src/up2date_client/up2dateErrors.py:295
msgid ""
"\n"
"    Your organization does not have enough Management entitlements to "
"register this\n"
"    system. Please notify your organization administrator of this error.\n"
"    You should be able to register this system after your organization frees "
"existing\n"
"    or purchases additional entitlements. Additional entitlements may be "
"purchased by your\n"
"    organization administrator in the SUSE Customer Center.\n"
"\n"
"    A common cause of this error code is due to having mistakenly setup an\n"
"    Activation Key which is set as the universal default.  If an activation "
"key is set\n"
"    on the account as a universal default, you can disable this key and "
"retry to avoid\n"
"    requiring a Management entitlement."
msgstr ""
"\n"
"    La vostra organització no té prou drets de gestió per registrar aquest\n"
"    sistema. Aviseu l'administrador de l'organització d'aquest error.\n"
"    Hauríeu de poder registrar aquest sistema després que la vostra "
"organització alliberi els drets\n"
"    existents o en compri d'addicionals. Els administrador de l'organització "
"poden adquirir\n"
"     drets addicionals al Centre d'atenció de l'usuari de SUSE.\n"
"\n"
"    Una causa comuna d'aquest codi d'error es deu a haver configurat per "
"error una\n"
"    clau d'activació que s'estableix com a predeterminada universal. Si "
"s'estableix una clau d'activació\n"
"    al compte com a predeterminada universal, podeu desactivar-la i tornar-"
"ho a intentar per evitar\n"
"    que requereixin un dret de gestió."

#~ msgid "Warning: unable to enable rhnsd with systemd"
#~ msgstr "Advertència: no s'ha pogut habilitar rhnsd amb systemd"

#~ msgid "Warning: unable to enable rhnsd with chkconfig"
#~ msgstr "Advertència: no s'ha pogut habilitar rhnsd amb chkconfig"
