# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Bettina De Monti <bdemonti@redhat.it>, 2001.
# Francesco Valente <fvalen@redhat.com>, 2003-2004.
# Lorenzo Stobbione <lorenzo.stobbione@clsengineering.it>, 2004-2007.
# Miroslav Suchý <msuchy@redhat.com>, 2011.
# Valentina Besi <valentina@redhat.it>, 2001,2012.
# Bettina De Monti <bdemonti@redhat.it>, 2001
# fvalen <fvalen@redhat.com>, 2003-2004
# Lorenzo Stobbione <lorenzo.stobbione@clsengineering.it>, 2004-2007
# Miroslav Suchý <msuchy@redhat.com>, 2011
# tavanofabio <tavano.fabio@gmail.com>, 2013
# Valentina Besi <valentina@redhat.it>, 2001,2012
# Jan Dobes <jdobes@redhat.com>, 2016. #zanata
# Jiri Dostal <jdostal@redhat.com>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-04-08 15:54+0200\n"
"PO-Revision-Date: 2020-12-26 18:27+0000\n"
"Last-Translator: Paolo Za <zapaolo@email.it>\n"
"Language-Team: Italian <https://l10n.opensuse.org/projects/uyuni/spacewalk-"
"client-tools/it/>\n"
"Language: it\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: Weblate 3.6.1\n"

#: ../src/up2date_client/capabilities.py:94
#, python-format
msgid ""
"This client requires the server to support %s, which the current server does "
"not support"
msgstr ""
"Questo client neccessita il supporto di %s da parte del server, poichè il "
"server attuale non lo supporta"

#: ../src/up2date_client/config.py:162
#, python-format
msgid "%s was not found"
msgstr "%s non è stato trovato"

#: ../src/up2date_client/rpcServer.py:56
msgid "Error: Server Unavailable. Please try later."
msgstr "Errore: Server Non disponibile. Riprovare più tardi."

#: ../src/up2date_client/rpcServer.py:182
#, fuzzy
msgid "ERROR: can not find server CA file"
msgstr "ERROR: impossibile trovare il file RHNS CA"

#: ../src/up2date_client/rpcServer.py:220
msgid "Connection aborted by the user"
msgstr "Connessione interrotta dall'utente"

#: ../src/up2date_client/rpcServer.py:268
msgid "Server has refused connection due to high load"
msgstr "Il server ha rifiutato la connessione a causa del traffico intenso"

#: ../src/up2date_client/up2dateErrors.py:47
#: ../src/up2date_client/up2dateErrors.py:80
#, python-format
msgid "class %s has no attribute '%s'"
msgstr "la classe %s non ha alcun attributo '%s'"

#: ../src/up2date_client/up2dateErrors.py:107
msgid "RPM error.  The message was:\n"
msgstr "errore RPM. Il messaggio è:\n"

#: ../src/up2date_client/up2dateErrors.py:114
msgid "Password error. The message was:\n"
msgstr "Errore della password. Il messaggio è:\n"

#: ../src/up2date_client/up2dateErrors.py:118
msgid "RPM dependency error. The message was:\n"
msgstr "Errore causato da una dipendenza RPM. Il messaggio era:\n"

#: ../src/up2date_client/up2dateErrors.py:128
msgid "Error communicating with server. The message was:\n"
msgstr "Errore di comunicazione con il server. Il messaggio era:\n"

#: ../src/up2date_client/up2dateErrors.py:135
msgid "File Not Found: \n"
msgstr "File non disponibile: \n"

#: ../src/up2date_client/up2dateErrors.py:142
msgid "Delay error from server.  The message was:\n"
msgstr "Errore di ritardo dal server. Il messaggio è:\n"

#: ../src/up2date_client/up2dateErrors.py:178
msgid "Error validating data at server:\n"
msgstr "Errore di convalida dei dati nel server:\n"

#: ../src/up2date_client/up2dateErrors.py:191
msgid ""
"\n"
"Red Hat Network Classic is not supported.\n"
"    "
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:197
msgid "The installation number is invalid"
msgstr "Il numero d'installazione non è valido"

#: ../src/up2date_client/up2dateErrors.py:200
msgid "Error parsing the oemInfo file at field:\n"
msgstr "Errore di analisi del file oemInfo nel campo:\n"

#: ../src/up2date_client/up2dateErrors.py:227
msgid "Network error: "
msgstr "Errore di rete: "

#: ../src/up2date_client/up2dateErrors.py:295
#, fuzzy
msgid ""
"\n"
"    Your organization does not have enough Management entitlements to "
"register this\n"
"    system. Please notify your organization administrator of this error.\n"
"    You should be able to register this system after your organization frees "
"existing\n"
"    or purchases additional entitlements. Additional entitlements may be "
"purchased by your\n"
"    organization administrator in the SUSE Customer Center.\n"
"\n"
"    A common cause of this error code is due to having mistakenly setup an\n"
"    Activation Key which is set as the universal default.  If an activation "
"key is set\n"
"    on the account as a universal default, you can disable this key and "
"retry to avoid\n"
"    requiring a Management entitlement."
msgstr ""
"\n"
"    L'organizzazione non ha un numero sufficiente di entitlement di Gestione "
"per registrare questo sistema\n"
"    con il Red Hat Network. Notificare questo errore all'amministratore "
"dell'organizzazione.\n"
"    Sarà possibile registrare questo sistema solo se l'organizzazione rende "
"disponibile o acquista entitlement aggiuntivi\n"
"    Gli entitlement aggiuntivi possono essere acquistati dall'amministratore "
"dell'organizzazione eseguendo un log in nel Red Hat Network\n"
"visitando la pagina 'Gestione sottoscrizioni' nella sezione 'Il tuo RHN di "
"RHN.\n"
"    \n"
"    Una causa comune per questo codice d'errore è l'impostazione errata di "
"una\n"
"    chiave di attivazione la quale viene impostata come default universale. "
"Se una chiave di attivazione è stata\n"
"    impostata per un account come default universale, sarà possibile "
"disabilitare la suddetta chiave\n"
"    evitando cosi la necessità di acquisire un entitlement di Gestione."

#, fuzzy
#~ msgid "Warning: unable to enable rhnsd with systemd"
#~ msgstr "Avvertenza: impossibile attivare rhnsd con chkconfig"

#~ msgid "Warning: unable to enable rhnsd with chkconfig"
#~ msgstr "Avvertenza: impossibile attivare rhnsd con chkconfig"
