# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Andrew Martynov <andrewm@inventa.ru>, 2004-2005.
# Artyom Kunyov <artkun@guitarplayer.ru>, 2012.
#   <iya777@yandex.ru>, 2012.
# Leonid Kanter <leon@geon.donetsk.ua>, 2003.
# Miroslav Suchý <msuchy@redhat.com>, 2011.
# Vladimir Lazarenko <vlad@lazarenko.net>, 2004.
# Yulia Poyarkova <ypoyarko@redhat.com>, 2006.
# Yulia <ypoyarko@redhat.com>, 2006-2007,2010-2011.
# Andrew Martynov <andrewm@inventa.ru>, 2004-2005
# Artyom Kunyov <artkun@guitarplayer.ru>, 2012
# triplepointfive <iya777@yandex.ru>, 2012
# Leonid Kanter <leon@geon.donetsk.ua>, 2003
# Mikhail Zholobov <legal90@gmail.com>, 2013
# Miroslav Suchý <msuchy@redhat.com>, 2011
# Vladimir Lazarenko <vlad@lazarenko.net>, 2004
# Yulia Poyarkova <ypoyarko@redhat.com>, 2006
# Yulia <ypoyarko@redhat.com>, 2006-2007,2010-2011
# Jan Dobes <jdobes@redhat.com>, 2016. #zanata
# Jiri Dostal <jdostal@redhat.com>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-04-08 15:54+0200\n"
"PO-Revision-Date: 2018-03-16 11:03+0000\n"
"Last-Translator: Copied by Zanata <copied-by-zanata@zanata.org>\n"
"Language-Team: Russian (http://www.transifex.com/projects/p/spacewalk/"
"language/ru/)\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
"X-Generator: Zanata 4.6.2\n"

#: ../src/up2date_client/capabilities.py:94
#, python-format
msgid ""
"This client requires the server to support %s, which the current server does "
"not support"
msgstr "Клиент требует от сервера поддержки %s, которую сервер не осуществляет"

#: ../src/up2date_client/config.py:162
#, python-format
msgid "%s was not found"
msgstr "%s не найден"

#: ../src/up2date_client/rpcServer.py:56
msgid "Error: Server Unavailable. Please try later."
msgstr "Ошибка: сервер недоступен. Повторите попытку позже."

#: ../src/up2date_client/rpcServer.py:182
#, fuzzy
msgid "ERROR: can not find server CA file"
msgstr "ОШИБКА: файл RHNS CA не найден"

#: ../src/up2date_client/rpcServer.py:220
msgid "Connection aborted by the user"
msgstr "Соединение прервано пользователем"

#: ../src/up2date_client/rpcServer.py:268
msgid "Server has refused connection due to high load"
msgstr "Сервер отказал в соединении по причине высокой загрузки"

#: ../src/up2date_client/up2dateErrors.py:47
#: ../src/up2date_client/up2dateErrors.py:80
#, python-format
msgid "class %s has no attribute '%s'"
msgstr "класс %s не содержит атрибут «%s»"

#: ../src/up2date_client/up2dateErrors.py:107
msgid "RPM error.  The message was:\n"
msgstr "Ошибка RPM. Сообщение:\n"

#: ../src/up2date_client/up2dateErrors.py:114
msgid "Password error. The message was:\n"
msgstr "Ошибка пароля. Сообщение:\n"

#: ../src/up2date_client/up2dateErrors.py:118
msgid "RPM dependency error. The message was:\n"
msgstr "Ошибка зависимостей RPM.  Сообщение:\n"

#: ../src/up2date_client/up2dateErrors.py:128
msgid "Error communicating with server. The message was:\n"
msgstr "Ошибка соединения с сервером. Сообщение:\n"

#: ../src/up2date_client/up2dateErrors.py:135
msgid "File Not Found: \n"
msgstr "Файл не найден: \n"

#: ../src/up2date_client/up2dateErrors.py:142
msgid "Delay error from server.  The message was:\n"
msgstr "Ошибка задержки от сервера. Сообщение:\n"

#: ../src/up2date_client/up2dateErrors.py:178
msgid "Error validating data at server:\n"
msgstr "Ошибка проверки данных на сервере:\n"

#: ../src/up2date_client/up2dateErrors.py:191
msgid ""
"\n"
"Red Hat Network Classic is not supported.\n"
"    "
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:197
msgid "The installation number is invalid"
msgstr "Неверный код установки"

#: ../src/up2date_client/up2dateErrors.py:200
msgid "Error parsing the oemInfo file at field:\n"
msgstr "Ошибка обработки файла oemInfo в поле:\n"

#: ../src/up2date_client/up2dateErrors.py:227
msgid "Network error: "
msgstr "Ошибка сети: "

#: ../src/up2date_client/up2dateErrors.py:295
#, fuzzy
msgid ""
"\n"
"    Your organization does not have enough Management entitlements to "
"register this\n"
"    system. Please notify your organization administrator of this error.\n"
"    You should be able to register this system after your organization frees "
"existing\n"
"    or purchases additional entitlements. Additional entitlements may be "
"purchased by your\n"
"    organization administrator in the SUSE Customer Center.\n"
"\n"
"    A common cause of this error code is due to having mistakenly setup an\n"
"    Activation Key which is set as the universal default.  If an activation "
"key is set\n"
"    on the account as a universal default, you can disable this key and "
"retry to avoid\n"
"    requiring a Management entitlement."
msgstr ""
"\n"
"    Недостаточно полномочий управления для регистрации системы в\n"
"    Red Hat Network. Сообщите об этом вашему администратору организации.\n"
"    После освобождения организацией существующих или \n"
"    приобретения новых полномочий вы сможете зарегистрировать систему.\n"
"    Новые полномочия администратор может приобрести после авторизации в     "
"Red Hat Network на странице «Ваша RHN - Управление подпиской».\n"
"    \n"
"    Типичной причиной этой ошибки является неверная настройка\n"
"    ключа активации в качестве используемого по умолчанию универсального "
"ключа.\n"
"    В этом случае можно отключить ключ и постараться избегать необходимости\n"
"    использования полномочия управления."

#, fuzzy
#~ msgid "Warning: unable to enable rhnsd with systemd"
#~ msgstr "Внимание: невозможно включить rhnsd с chkconfig"

#~ msgid "Warning: unable to enable rhnsd with chkconfig"
#~ msgstr "Внимание: невозможно включить rhnsd с chkconfig"
